In [1]:
import numpy as np
import pandas as pd

url = 'https://fr.wikipedia.org/wiki/Lithium'

tables = pd.read_html(url, match='Pays')
if tables:
    dfLith = tables[0]

    print(dfLith)
else:
    print("Aucune table trouvée sur la page.")

                                Pays Production 2018 Production 2019  \
0                          Argentine           6 400           6 300
1                          Australie          58 800          45 000
2                            Bolivie              nd              nd
3                             Brésil             300           2 400
4                             Canada           2 400             200
5                              Chili          17 000          19 300
6                              Chine           7 100          10 800
7   République démocratique du Congo              nd              nd
8                 États-Unis[48],[b]             900             900
9                          Allemagne              nd              nd
10                           Mexique              nd              nd
11            République tchèque[49]              nd              nd
12                             Pérou              nd              nd
13                           Espagne              nd              nd
14                          Portugal             800             900
15                              Mali              nd              nd
16                            Russie              nd              nd
17                            Serbie              nd              nd
18                          Zimbabwe           1 600           1 200
19                       Autres pays             NaN             NaN
20                     Total mondial          95 000          86 000

   Production 2020 Production 2021 Production 2022 estimée Réserves prouvées  \
0            5 900           5 970                   6 200         2 700 000
1           39 700          55 300                  61 000         6 200 000
2               nd              nd                      nd                nd
3            1 420           1 700                   2 200           250 000
4               nd              nd                     500           930 000
5           21 500          28 300                  39 000         9 300 000
6           13 300          14 000                  19 000         2 000 000
7               nd              nd                      nd                nd
8              900              nd                     900         1 000 000
9               nd              nd                      nd                nd
10              nd              nd                      nd                nd
11              nd              nd                      nd                nd
12              nd              nd                      nd                nd
13              nd              nd                      nd                nd
14             348             900                     600            60 000
15              nd              nd                      nd                nd
16              nd              nd                      nd                nd
17              nd              nd                      nd                nd
18             417             710                     800           310 000
19             NaN             NaN                     NaN         3 300 000
20          82 500         107 000                 130 000        26 000 000

   Ressources estimées
0           20 000 000
1            7 900 000
2           21 000 000
3              730 000
4            2 900 000
5           11 000 000
6            6 800 000
7            3 000 000
8           12 000 000
9            3 200 000
10           1 700 000
11           1 300 000
12             880 000
13             320 000
14             270 000
15             840 000
16           1 000 000
17           1 200 000
18             690 000
19                 NaN
20          98 000 000

In [2]:
dfLith.head()

,Pays,Production 2018,Production 2019,Production 2020,Production 2021,Production 2022 estimée,Réserves prouvées,Ressources estimées
0,Argentine,6 400,6 300,5 900,5 970,6 200,2 700 000,20 000 000
1,Australie,58 800,45 000,39 700,55 300,61 000,6 200 000,7 900 000
2,Bolivie,nd,nd,nd,nd,nd,nd,21 000 000
3,Brésil,300,2 400,1 420,1 700,2 200,250 000,730 000
4,Canada,2 400,200,nd,nd,500,930 000,2 900 000

In [3]:
dfLith['Métal'] = 'Lithium'
dfLith.head()

,Pays,Production 2018,Production 2019,Production 2020,Production 2021,Production 2022 estimée,Réserves prouvées,Ressources estimées,Métal
0,Argentine,6 400,6 300,5 900,5 970,6 200,2 700 000,20 000 000,Lithium
1,Australie,58 800,45 000,39 700,55 300,61 000,6 200 000,7 900 000,Lithium
2,Bolivie,nd,nd,nd,nd,nd,nd,21 000 000,Lithium
3,Brésil,300,2 400,1 420,1 700,2 200,250 000,730 000,Lithium
4,Canada,2 400,200,nd,nd,500,930 000,2 900 000,Lithium

In [4]:
url = 'https://fr.wikipedia.org/wiki/Cobalt'

tables = pd.read_html(url, match='Pays')
if tables:
    dfCob = tables[0]

    print(dfCob)
else:
    print("Aucune table trouvée sur la page.")

                                Pays    2013    2014    2015    2016    2017  \
0   République démocratique du Congo  54 000  63 000  63 000  64 000  73 000
1                             Russie   6 300   6 300   6 200   5 500   5 900
2                          Australie   6 400   5 980   6 000   5 500   5 030
3                             Canada   6 920   6 570   6 900   4 250   3 870
4                        Philippines       -       -   4 300   4 100   4 600
5                               Cuba   4 200   3 700   4 300   4 200   5 000
6                         Madagascar       -   3 100   3 700   3 800   3 500
7          Papouasie-Nouvelle-Guinée       -       -       -   2 190   3 310
8                     Afrique du Sud   3 000   3 000   3 000   2 300   2 300
9                              Maroc   2 100       -       -       -   2 200
10                             Chine   7 200   7 200   7 700   7 700   3 100
11                        États-Unis       -       -     760     690     640

       2018     2019    2020     2021     2022   réserves
0   104 000  100 000  95 000  119 000  130 000  4 000 000
1     6 100    6 300   6 300    8 000    8 900    250 000
2     4 880    5 740   5 700    5 295    5 900  1 500 000
3     3 520    3 340   3 200    4 361    3 900    220 000
4     4 600    5 100   4 700    3 600    3 800    260 000
5     3 500    3 800   3 600    4 000    3 800    500 000
6     3 300    3 400     700        -    3 000    100 000
7     3 280    2 910   2 800    2 953    3 000     47 000
8     2 300    2 100   1 800        -        -          -
9     2 100    2 300   1 900    2 300    2 300     13 000
10    2 000    2 500   2 300    2 200    2 200    140 000
11      490      500     600      650      800      69000

In [5]:
dfCob['Métal'] = 'Cobalt'
dfCob.head()

,Pays,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,réserves,Métal
0,République démocratique du Congo,54 000,63 000,63 000,64 000,73 000,104 000,100 000,95 000,119 000,130 000,4 000 000,Cobalt
1,Russie,6 300,6 300,6 200,5 500,5 900,6 100,6 300,6 300,8 000,8 900,250 000,Cobalt
2,Australie,6 400,5 980,6 000,5 500,5 030,4 880,5 740,5 700,5 295,5 900,1 500 000,Cobalt
3,Canada,6 920,6 570,6 900,4 250,3 870,3 520,3 340,3 200,4 361,3 900,220 000,Cobalt
4,Philippines,-,-,4 300,4 100,4 600,4 600,5 100,4 700,3 600,3 800,260 000,Cobalt

In [6]:
url = 'https://fr.wikipedia.org/wiki/Cuivre'

tables = pd.read_html(url, match='Pays')
if tables:
    dfCui = tables[0]

    print(dfCui)
else:
    print("Aucune table trouvée sur la page.")

     Rang                              Pays Production 2020 (kt)  % mondial
0       1                             Chili                5 700        285
1       2                             Pérou                2 200        110
2       3                             Chine                1 700         85
3       4                        États-Unis                1 200         60
4       5  République démocratique du Congo                1 300         65
5       6                         Australie                  870         44
6       7                            Zambie                  830         42
7       8                           Mexique                  690         35
8       9                            Russie                  850         43
9      10                        Kazakhstan                  580         29
10     11                            Canada                  570         29
11     12                         Indonésie                  380         17
12    NaN                            autres                  370        185
13  Monde                             Monde               20 000        100

In [7]:
url = 'https://ressources-naturelles.canada.ca/nos-ressources-naturelles/mines-materiaux/donnees-statistiques-et-analyses-sur-lexploitation-miniere/faits-mineraux-metaux/faits-sur-laluminium/20568'

tables = pd.read_html(url, match='Bahreïn')
if tables:
    dfAlu = tables[0]

    print(dfAlu)
else:
    print("Aucune table trouvée sur la page.")

         Classement                 Pays Milliers de tonnes  \
0                 1                Chine             40 000
1                 2                 Inde              4 000
2                 3               Russie              3 700
3                 4               Canada              3 000
4                 5  Émirats arabes unis              2 700
5                 6              Bahreïn              1 600
6                 7            Australie              1 500
7                 8              Norvège              1 400
8                 9           États-Unis                860
9                10              Islande                750
10              NaN          Autres pays              9 100
11  Total (arrondi)                  NaN             69 000

   Pourcentage du total
0                58,3 %
1                 5,8 %
2                 5,4 %
3                 4,4 %
4                 3,9 %
5                 2,3 %
6                 2,2 %
7                 2,0 %
8                 1,3 %
9                 1,1 %
10               13,3 %
11              100,0 %